### ISSUE TITLE
What's the purpose of Maven

### ISSUE THREAD

**Issue by igorgorbunov3333** [qala-io/java-course#3]
What's the point in Maven while, for example, Intellij IDEA can do the same staff e.g. run tests, making war packages (I don't say about mavens dependencies feature)? If I have added test plugin to pom.xml than tests should run each time while application run (or for example clean 'target' directory if I have added clean plugin)?

**Comment by ctapobep** [comment]
First of all IntelliJ is just one IDE, there are others like NetBeans, Eclipse. What if some of your colleagues work in Eclipse? Then IntelliJ configs won't work for them.

But there are bigger problems that Maven solves:

* It manages external dependencies. If your code depends on other libraries (and often there are hundreds of them in an average project), then you'll either have to keep those locally right in VCS (which would take a lot of space and is simply harder when you need to update a bunch of them) or each person would have to keep them locally and configure project manually by adding libraries to IDE.
* It standardizes projects. You'll learn Maven structure just once and then every other project will have the same structure and similar plugin settings.
* It standardizes project settings for IDEs - all modern IDEs can read pom.xml and figure out which dependencies to include and what to do during compilation/testing/etc.
* It works on Build Servers. We don't create binaries (like war files) locally for production. We commit changes to VCS and then a Build Server downloads the changes and builds the artifacts. Build Servers don't have IDEs installed.

PS: this course is intended for people with experience, it's going to be too complicated otherwise. If you haven't participated in any real projects before I'd strongly advise to search for courses for beginners.
